### ISSUE TITLE
How does this model compare to other models specifically designed for atomic environments?

### ISSUE THREAD

**Issue by bartolsthoorn** [mariogeiger/se3cnn#1]
The protein structure classification problem is interesting, but if I understood the paper correctly you fix the positions to a grid. This is an approximation, so I wonder how this compares to rotationally invariant models that work with directly with continuous positions.

There are two recent models/approaches that have these properties:
- Smooth Overlap of Atomic Positions (SOAP) https://arxiv.org/abs/1209.3140
- Continuous-filter convolutional neural network https://arxiv.org/abs/1712.06113

These models have a cut-off radius for local environments which makes them different as well but it would be very interesting to see how well these approaches classify the structures. Did you look at these?
I am not affiliated with these works, just interested in the problem :)

**Comment by mauriceweiler** [comment]
You are right, in our implementation we target on data which is voxelized on an Euclidean grid. Our theory is derived in the continuum and seems to be well suited to your application if an appropriate discretization of the continuous theory is chosen. Choosing a discretization to a regular grid, as done in our code, should be okay as long as you sample the mesh fine enough but this can become very memory extensive.
Alternatively, you could discretize the continuous theory by sampling it at a point cloud. IIRC this discretization is chosen in SchNet (your 2nd link) but from a quick skimming it doesn't seem that their network is rotationally equivariant.
You can also have a look at 'Tensor Field Networks' (TFNs, https://arxiv.org/abs/1802.08219) which are rotationally equivariant and sampled at a point cloud. To make the comparison to our work: The authors of TFN don't _derive_ their kernel basis as a _complete_ basis of intertwiners (equivariant linear maps) between Wiegner D matrices (the irreps of SO(3)) as we do. Instead, their kernel space is introduced as _some_ space of SO(3) equivariant maps. In the end of the day both convolutional layers are equivalent though up to the discretization. It seems like TFN is using 'norm nonlinearities'. We tried both 'norm nonlinearities' and 'gated nonlinearities' and found that the latter seem to work better.

**Comment by bartolsthoorn** [comment]
Thank you for your detailed reply!
