### ISSUE TITLE
pickle data was truncated

### ISSUE THREAD

**Issue by DRM-Free** [mariogeiger/se3cnn#11]
I simply followed the install instructions and run examples/example.py and got the following error
Exception has occurred: _pickle.UnpicklingError
pickle data was truncated
  File "${workspace}/se3cnn/examples/tetris_point.py", line 59, in forward
    output = conv(output, difference_mat)

**Comment by mariogeiger** [comment]
`tetris_point.py` changed since then. Can you retry with the code in branch `point` ? and tell me if it's still crashing.
