### ISSUE TITLE
real_spherical_harmonics.rsh float32

### ISSUE THREAD

**Issue by L-sky** [mariogeiger/se3cnn#39]
As @bkmi recently encountered, `rsh` (silently) runs into undefined behavior and outputs garbage when supplied with float32 inputs instead of float64. 

I see 3 possible ways to handle this: 
1. Allow proper calculations for float32 via templates in rsh_cuda.cu.
2. Soft force float64 via float32 -> float64 -> float32 type casting (rsh calculations remain in float64).
3. Hard force float64 with assert.

**Comment by mariogeiger** [comment]
That’s problematic. We can start with 3 and do 1 later.

**Comment by L-sky** [comment]
1. is pretty much `double -> replace all`. The only thing I don't know right now is specific commands for type check of tensors within C++ layer, but shouldn't be too hard. 
Are there any additional considerations to have in mind?

**Comment by mariogeiger** [comment]
fixed in #41
