### ISSUE TITLE
sh=None in point Kernel leads to error (rather than using default)

### ISSUE THREAD

**Issue by blondegeek** [mariogeiger/se3cnn#45]
This breaks the tutorial. If this is the new default behavior, let me know so I can update the tutorials. Please advise @L-sky and @mariogeiger.

**Comment by L-sky** [comment]
It was me moving assignment of default function from inside of a function to signature. 
Code is going to work consistently for both newer and older versions of code if you omit `sh` parameter, instead of passing None.

**Comment by blondegeek** [comment]
I'll update the tutorials accordingly.
